"""Plot robustness curves from combined_robustness_results.csv.

The input CSV is expected to be generated by src/summarize_robustness.py.

Example:
    python src/plot_robustness_curves.py \
        --input-csv results/robustness/combined_robustness_results.csv \
        --out-dir results/figures
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable, List

import matplotlib.pyplot as plt
import pandas as pd

DEFAULT_METRICS = ["top1_accuracy", "macro_f1"]


def as_numeric_severity(df: pd.DataFrame) -> pd.DataFrame:
    result = df.copy()
    result["severity_numeric"] = pd.to_numeric(result["severity"], errors="coerce")
    return result


def plot_metric_for_degradation(df: pd.DataFrame, degradation: str, metric: str, out_dir: Path) -> Path:
    sub = df[df["degradation"] == degradation].copy()
    if sub.empty:
        raise ValueError(f"No rows found for degradation={degradation}")

    sub = as_numeric_severity(sub)
    sub = sub.dropna(subset=["severity_numeric", metric])
    if sub.empty:
        raise ValueError(f"No plottable rows found for degradation={degradation}, metric={metric}")

    plt.figure(figsize=(7, 5))
    for model, model_df in sub.groupby("model"):
        model_df = model_df.sort_values("severity_numeric")
        plt.plot(model_df["severity_numeric"], model_df[metric], marker="o", label=model)

    plt.xlabel("Severity")
    plt.ylabel(metric.replace("_", " ").title())
    plt.title(f"Robustness to {degradation}: {metric.replace('_', ' ').title()}")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"robustness_{degradation}_{metric}.png"
    plt.savefig(out_path, dpi=200)
    plt.close()
    return out_path


def plot_all(input_csv: Path, out_dir: Path, metrics: Iterable[str]) -> List[Path]:
    df = pd.read_csv(input_csv)
    required_cols = {"model", "degradation", "severity"}
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(f"Input CSV is missing required columns: {sorted(missing)}")

    generated: List[Path] = []
    degradations = [d for d in sorted(df["degradation"].dropna().unique()) if d != "clean"]

    for degradation in degradations:
        for metric in metrics:
            if metric not in df.columns:
                print(f"[skip] Metric column not found: {metric}")
                continue
            try:
                out_path = plot_metric_for_degradation(df, degradation, metric, out_dir)
            except ValueError as exc:
                print(f"[skip] {exc}")
                continue
            generated.append(out_path)
            print(f"Saved: {out_path}")

    if not generated:
        raise RuntimeError("No figures were generated. Check the input CSV content.")
    return generated


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot robustness curves.")
    parser.add_argument("--input-csv", type=Path, default=Path("results/robustness/combined_robustness_results.csv"))
    parser.add_argument("--out-dir", type=Path, default=Path("results/figures"))
    parser.add_argument("--metrics", nargs="+", default=DEFAULT_METRICS)
    args = parser.parse_args()

    plot_all(args.input_csv, args.out_dir, args.metrics)


if __name__ == "__main__":
    main()
